apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: comp.vpcs.ec2.aws.mfdev.com
  labels:
    crossplane.io/xrd: xrds.vpcs.ec2.aws.mfdev.com
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: ec2.aws.mfdev.com/v1alpha1
    kind: XVPC
  resources:
  - name: vpc
    base:
      apiVersion: ec2.aws.crossplane.io/v1beta1
      kind: VPC
      metadata: {} # PATCHED
      spec:
        forProvider: {} # PATCHED
          # cidrBlock: 10.0.0.0/16
          # region: us-east-1 
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.forProvider.region
      toFieldPath: spec.forProvider.region
    - type: FromCompositeFieldPath
      fromFieldPath: spec.forProvider.cidrBlock
      toFieldPath: spec.forProvider.cidrBlock
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.name